services:
  backend:
    build:
      context: ./backend
    container_name: microinvoice-backend
    ports:
      - "${APP_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: microinvoice-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:17.5
    container_name: microinvoice-db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  db_data:
